//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmsalemLogic.NewLogic.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidByUsTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaidByUsTransaction()
        {
            this.PaidByUsCreditCardTransactionLog = new HashSet<PaidByUsCreditCardTransactionLog>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> OriginAmount { get; set; }
        public string OriginalCurrencyCode { get; set; }
        public Nullable<decimal> BillingAmount { get; set; }
        public string BillingCurrencyCode { get; set; }
        public string SupplierAccountNum { get; set; }
        public string SupplierName { get; set; }
        public string BackOfficeCompany { get; set; }
        public string TripNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ForWho { get; set; }
        public string Item { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaidByUsCreditCardTransactionLog> PaidByUsCreditCardTransactionLog { get; set; }
    }
}
